### ISSUE TITLE
lots of compile errors on linux

### ISSUE THREAD

**Issue by gery** [rhx/SwiftHelloGtk#10]
OS: Ubuntu 20.04.2 LTS (Focal Fossa)
Swift version 5.3.2 (swift-5.3.2-RELEASE)

Error Logs:

/home/gery/Downloads/SwiftHelloGtk-main/.build/checkouts/SwiftGLib/Sources/GLib/Time.swift:24:47: error: cannot find 'SourceFunc' in scope
    let callback = unsafeBitCast(handler, to: SourceFunc.self)
                                              ^~~~~~~~~~
/home/gery/Downloads/SwiftHelloGtk-main/.build/checkouts/SwiftGLib/Sources/GLib/Time.swift:25:14: error: cannot find 'timeoutAddFull' in scope
    let rv = timeoutAddFull(priority: p, interval: interval, function: callback, data: opaqueHolder) {
             ^~~~~~~~~~~~~~
/home/gery/Downloads/SwiftHelloGtk-main/.build/checkouts/SwiftGLib/Sources/GLib/Error.swift:17:33: error: cannot find type 'ErrorRef' in scope
public typealias GLibErrorRef = ErrorRef

And many others......

**Comment by mikolasstuchlik** [comment]
https://github.com/rhx/SwiftGtk/issues/47

**Comment by rhx** [comment]
I'm closing this for the moment.  Let me know if you still have issues after running `./run-gir2swift.sh` (see README.md).
