### ISSUE TITLE
Building on Ubuntu 20.04 produces no executable

### ISSUE THREAD

**Issue by DanBurkhardt** [rhx/SwiftHelloGtk#5]
**Local Config**

- Ubuntu 20.04
- Swift Version 5.2.5
- All dependencies installed via README.md instructions to enable SwiftGtk

**Issues**

- I am following all of the instructions in the README. 
- The product builds and runs as expected using Xcode on macOS 10.15
- Cloning the same repo in the Ubuntu env, installing all deps and running `./build.sh` starts the build process. However, once it is finished, there is no output application as there was in macOS.

**Potential Resolutions / Suggestions**

- It could be that I don't understand something here. There is a folder named "x86_64-unknown-linux-gnu" under `.build/`, but no executable
    - If I am missing something here, could you please update the README?
- Potentially, this latest version does not product an executable for Ubuntu 20.04 machines.

**Comment by rhx** [comment]
Yes, there were some remaining issues under Ubuntu that have been fixed now.   Can you try
```
./distclean.sh
git pull
./build.sh
```
and see if this works for you now?

**Comment by DanBurkhardt** [comment]
Sorry I never got a chance to test this, i’m sure it’s fixed, will circle back if I have the issue again
