### ISSUE TITLE
Shell scripts giving syntax errors and "No such file or directory" errors

### ISSUE THREAD

**Issue by Clocks-in-a-Cooler** [rhx/SwiftHelloGtk#6]
I've installed the required libraries and cloned the repository. Running `build.sh` gives these messages:
```
: No such file or directoryg.sh
: No such file or directoryrate-wrapper.sh
; use --help to list available arguments
./build.sh: line 15: syntax error: unexpected end of file
```
Running `config.sh` directly:
```
./config.sh: line 27: syntax error near unexpected token `else'
'/config.sh: line 27: `   else if which gtac >/dev/null ; then
```
Running `distclean.sh`:
```
: No such file or directoryonfig.sh
: No such file or directorylean.sh
```
I also get these errors when trying to build gir2swift and the other SwiftGtk examples.

I'm running Ubuntu 20.04.1, bash 5.0.17, Swift 5.2.5

Maybe this is a problem with bash?

**Comment by rhx** [comment]
Thanks, this was an issue with spurious error output. I have redirected stderr to `/dev/null` now.
